<?php

namespace Bestcasting\Manage\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BranchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getCollection()
    {
        return $this->findBy(['active' => 1]);
    }
}
