<?php

namespace Bestcasting\Manage\CoreBundle\Entity;

/**
 * BranchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchRepository extends \Doctrine\ORM\EntityRepository
{
}
