<?php

namespace Bestcasting\Manage\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param string $username
     * @param string $password
     */
    public function findByUsernameAndPassword($username, $password)
    {
        $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.');
    }
}
