<?php

namespace Manage\Bundle\castingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScreenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScreenRepository extends EntityRepository
{
}
